version: '3.9'

services:

  bot:
    image: 'kevinvt/discord-competition-bot:latest'
    container_name: bot
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
      - API_USER_USERNAME
      - API_USER_PASSWORD

  ui:
    image: 'kevinvt/scored-ui:latest'
    container_name: ui
    depends_on:
      - backend
    ports:
      - 4200:80 # exposes the ui on port 4200

  backend:
    image: 'kevinvt/scored-backend:latest'
    container_name: backend
    depends_on:
      - db
    ports:
      - 8080:8080 # exposes the backend on port 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=update # Should be uncommented for production
      - API_USER_USERNAME
      - API_USER_PASSWORD

  db:
    image: 'postgres:14.2-alpine'
    container_name: db
    volumes:
      - scored-db:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  scored-db:
